variables:
    GIT_STRATEGY: clone

stages:
    - test

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

job_1:
  stage: test
  image: 0b158dd36e5c
  script:
#    - pwd
#    - ls

    - cd src/cpu/aarch64/xbyak_translator_aarch64/translator/third_party/
    - mkdir build_xed_aarch64
    - cd build_xed_aarch64/
    - ../xed/mfile.py --host-cpu=aarch64 --shared install
    - cd kits/
    - XED=`ls | grep install`
    - ln -sf $XED xed
    - cd xed
    - export XED_ROOT_DIR=`pwd`
    - cd ../../../../
    - source dot.zshrc.xbyak
    - cd ../../../../../
    - mkdir build
    - cd build
    - export LD_LIBRARY_PATH=/github/workspace/src/cpu/aarch64/xbyak_translator_aarch64/translator/third_party/build_xed_aarch64/kits/xed/lib:${LD_LIBRARY_PATH} && \
    - cmake -DDNNL_INDIRECT_JIT_AARCH64=ON -DDNNL_TARGET_ARCH=AARCH64 -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=AARCH64 -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++  -DCMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu ..
    - make -j48
    - cd /
    - ./gtest_all.sh
