variables:
    GIT_STRATEGY: clone

stages:
    - test

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

job_1:
  stage: test
  image: 0b158dd36e5c
  script:
#    - pwd
#    - ls
    - export ONEDNN_ROOT_DIR=`pwd`
    - cd src/cpu/aarch64/xbyak_translator_aarch64/translator/third_party/
    - mkdir build_xed_aarch64
    - cd build_xed_aarch64/
    - ../xed/mfile.py --host-cpu=aarch64 --shared install
    - cd kits/
    - XED=`ls | grep install`
    - ln -sf $XED xed
    - cd xed
    - export XED_ROOT_DIR=`pwd`
    - cd ${ONEDNN_ROOT_DIR}    
    - mkdir build
    - cd build
    - export LD_LIBRARY_PATH=${XED_ROOT_DIR}/lib:${LD_LIBRARY_PATH} && \
    - cmake -DDNNL_INDIRECT_JIT_AARCH64=ON ..
    - make -j48
    - make test
